### ISSUE TITLE
websocket 怎么处理？

### ISSUE THREAD

**Issue by zhangn1985** [SeaHOH/ykdl#236]
在提交前，请确保您已经检查了以下内容!

- [ ] 你确实可以在浏览器或移动端中观看视频，但不能使用`ykdl`下载。
- [ ] 您的`ykdl`为最新版。
- [ ] 您已经阅读并按 <https://github.com/zhangn1985/ykdl/wiki> 中的指引进行了操作。
- [ ] 您的问题没有在 <https://github.com/zhangn1985/ykdl/issues> 报告，否则请在原有 issue 下报告。
- [ ] 本问题确实关于`ykdl`，而不是其他项目。

请将错误输出粘贴在下面:

```
python3 -m cykdl -i https://www.zhanqi.tv/naigege
http://dlhls.cdn.zhanqi.tv/zqlive//737_CGq78.m3u8
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/zhangn1985/source/ykdl/cykdl/__main__.py", line 185, in <module>
    main()
  File "/home/zhangn1985/source/ykdl/cykdl/__main__.py", line 163, in main
    info = parser(u)
  File "/home/zhangn1985/source/ykdl/ykdl/extractor.py", line 24, in parser
    info = self.prepare()
  File "/home/zhangn1985/source/ykdl/ykdl/extractors/zhanqi.py", line 29, in prepare
    info.stream_types, info.streams = load_m3u8_playlist(real_url)
  File "/home/zhangn1985/source/ykdl/ykdl/util/m3u8_wrap.py", line 26, in load_m3u8_playlist
    m = m3u8.load(url).playlists
  File "/usr/lib/python3/dist-packages/m3u8/__init__.py", line 43, in load
    return _load_from_uri(uri, timeout, headers)
  File "/usr/lib/python3/dist-packages/m3u8/__init__.py", line 52, in _load_from_uri
    resource = urlopen(request, timeout=timeout)
  File "/usr/lib/python3.5/urllib/request.py", line 163, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.5/urllib/request.py", line 472, in open
    response = meth(req, response)
  File "/usr/lib/python3.5/urllib/request.py", line 582, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.5/urllib/request.py", line 510, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 444, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 590, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

```

如果您有其他附言，例如问题只在某个视频发生，或者是一般性讨论或者提出新功能，请在下面添加:

> 

经简单分析，zhanqi启用的websocket， 那么python 如何处理websocket?

**Comment by wwqgtxx** [comment]
https://pypi.python.org/pypi/websocket-client/0.44.0
