### ISSUE TITLE
download for xiami.com not work

### ISSUE THREAD

**Issue by karma-sun** [SeaHOH/ykdl#243]
在提交前，请确保您已经检查了以下内容!

- [ ] 你确实可以在浏览器或移动端中观看视频，但不能使用`ykdl`下载。
- [ ] 您的问题没有在 <https://github.com/zhangn1985/ykdl/issues> 报告，否则请在原有 issue 下报告。
- [ ] 您的`ykdl`为最新版。
- [ ] 您已经阅读并按 <https://github.com/zhangn1985/ykdl/wiki> 中的指引进行了操作。
- [ ] 本问题确实关于`ykdl`，而不是其他项目。

请将错误输出粘贴在下面:
ykdl -i http://www.xiami.com/song/bf0yTHR31402
```
Traceback (most recent call last):
  File "C:\Python35\Scripts\ykdl-script.py", line 9, in <module>
    load_entry_point('ykdl==1.5.3', 'console_scripts', 'ykdl')()
  File "C:\Python35\lib\site-packages\ykdl-1.5.3-py3.5.egg\cykdl\__main__.py", l
ine 163, in main
  File "C:\Python35\lib\site-packages\ykdl-1.5.3-py3.5.egg\ykdl\extractor.py", l
ine 24, in parser
  File "C:\Python35\lib\site-packages\ykdl-1.5.3-py3.5.egg\ykdl\extractors\xiami
.py", line 47, in prepare
  File "C:\Python35\lib\site-packages\ykdl-1.5.3-py3.5.egg\ykdl\util\html.py", l
ine 65, in get_content
  File "C:\Python35\lib\urllib\request.py", line 163, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Python35\lib\urllib\request.py", line 472, in open
    response = meth(req, response)
  File "C:\Python35\lib\urllib\request.py", line 582, in http_response
    'http', request, response, code, msg, hdrs)
  File "C:\Python35\lib\urllib\request.py", line 510, in error
    return self._call_chain(*args)
  File "C:\Python35\lib\urllib\request.py", line 444, in _call_chain
    result = func(*args)
  File "C:\Python35\lib\urllib\request.py", line 590, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
```

如果您有其他附言，例如问题只在某个视频发生，或者是一般性讨论或者提出新功能，请在下面添加:

> [您的内容]

**Comment by zhangn1985** [comment]
目前还不知道怎么做。

**Comment by karma-sun** [comment]
虾米音乐要关闭了，相关代码可以删掉了
