### ISSUE TITLE
ERROR in douyu.com

### ISSUE THREAD

**Issue by hatienl0i261299** [SeaHOH/ykdl#561]
在提交前，请确保您已经检查了以下内容!

- [x] 你确实可以在浏览器或移动端中观看视频，但不能使用`ykdl`下载。
- [x] 您的`ykdl`为最新版。
- [x] 您已经阅读并按 <https://github.com/zhangn1985/ykdl/wiki> 中的指引进行了操作。
- [x] 您的问题没有在 <https://github.com/zhangn1985/ykdl/issues> 报告，否则请在原有 issue 下报告。
- [x] 本问题确实关于`ykdl`，而不是其他项目。

请将错误输出粘贴在下面:

```
[在这里粘贴完整日志]
```

如果您有其他附言，例如问题只在某个视频发生，或者是一般性讨论或者提出新功能，请在下面添加:

> [您的内容]

i Try to run `ykdl "https://www.douyu.com/594019" -p mpv`

So, here is error
```Traceback (most recent call last):
  File "C:\Python39\Scripts\ykdl-script.py", line 33, in <module>
    sys.exit(load_entry_point('ykdl==1.6.2', 'console_scripts', 'ykdl')())
  File "c:\python39\lib\site-packages\cykdl\__main__.py", line 173, in main
    info = parser(u)
  File "c:\python39\lib\site-packages\ykdl\extractor.py", line 24, in parser
    info = self.prepare()
  File "c:\python39\lib\site-packages\ykdl\extractors\douyu\live.py", line 39, in prepare
    html_content = get_content(api_url)
  File "c:\python39\lib\site-packages\ykdl\util\html.py", line 67, in get_content
    response = urlopen(req)
  File "c:\python39\lib\urllib\request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "c:\python39\lib\urllib\request.py", line 523, in open
    response = meth(req, response)
  File "c:\python39\lib\urllib\request.py", line 632, in http_response
    response = self.parent.error(
  File "c:\python39\lib\urllib\request.py", line 561, in error
    return self._call_chain(*args)
  File "c:\python39\lib\urllib\request.py", line 494, in _call_chain
    result = func(*args)
  File "c:\python39\lib\urllib\request.py", line 641, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
```

i installed mpv player
i hope you can fix it soon

**Comment by mengmo** [comment]
https://github.com/zhangn1985/ykdl#simple-installation-guide
> Packages on PyPI had been outdated, consider install via other package managers, or direct install from source.

**Comment by hatienl0i261299** [comment]
it work, ths you so much

**Comment by hatienl0i261299** [comment]
In CLI
`ykdl "https://www.douyu.com/594019" --json`
but i dont know how to get json in code
```
import ykdl
....
```
can you give a example, url ex `https://www.douyu.com/594019`

**Comment by SeaHOH** [comment]
The CLI itself is a example.
