### ISSUE TITLE
[失效] 黑白直播

### ISSUE THREAD

**Issue by TaoziDB** [SeaHOH/ykdl#573]
在提交前，请确保您已经检查了以下内容!

- [x] 你确实可以在浏览器或移动端中观看视频，但不能使用`ykdl`下载。
- [x] 您的`ykdl`为最新版。
- [x] 您已经阅读并按 <https://github.com/zhangn1985/ykdl/wiki> 中的指引进行了操作。
- [x] 您的问题没有在 <https://github.com/zhangn1985/ykdl/issues> 报告，否则请在原有 issue 下报告。
- [x] 本问题确实关于`ykdl`，而不是其他项目。

请将错误输出粘贴在下面:

```
>ykdl -i https://www.heibaizhibo.com/anchorLive/513780
Traceback (most recent call last):
  File "c:\program files (x86)\microsoft visual studio\shared\python37_64\lib\site-packages\ykdl\common.py", line 39, in url_to_module
    m = import_module('.'.join(['ykdl','extractors', short_name]))
  File "c:\program files (x86)\microsoft visual studio\shared\python37_64\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'ykdl.extractors.heibaizhibo'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\program files (x86)\microsoft visual studio\shared\python37_64\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\program files (x86)\microsoft visual studio\shared\python37_64\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\Scripts\ykdl.exe\__main__.py", line 7, in <module>
  File "c:\program files (x86)\microsoft visual studio\shared\python37_64\lib\site-packages\cykdl\__main__.py", line 204, in main
    m, u = url_to_module(url)
  File "c:\program files (x86)\microsoft visual studio\shared\python37_64\lib\site-packages\ykdl\common.py", line 47, in url_to_module
    new_url = get_location(url, headers = {})
  File "c:\program files (x86)\microsoft visual studio\shared\python37_64\lib\site-packages\ykdl\util\html.py", line 85, in get_location
    response = get_head_response(url, headers=headers)
  File "c:\program files (x86)\microsoft visual studio\shared\python37_64\lib\site-packages\ykdl\util\html.py", line 71, in get_head_response
    response = urlopen(req)
  File "c:\program files (x86)\microsoft visual studio\shared\python37_64\lib\urllib\request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "c:\program files (x86)\microsoft visual studio\shared\python37_64\lib\urllib\request.py", line 531, in open
    response = meth(req, response)
  File "c:\program files (x86)\microsoft visual studio\shared\python37_64\lib\urllib\request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "c:\program files (x86)\microsoft visual studio\shared\python37_64\lib\urllib\request.py", line 569, in error
    return self._call_chain(*args)
  File "c:\program files (x86)\microsoft visual studio\shared\python37_64\lib\urllib\request.py", line 503, in _call_chain
    result = func(*args)
  File "c:\program files (x86)\microsoft visual studio\shared\python37_64\lib\urllib\request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

```

如果您有其他附言，例如问题只在某个视频发生，或者是一般性讨论或者提出新功能，请在下面添加:

> 已更新到最新版本

**Comment by SeaHOH** [comment]
当前，此解析模块尚未发布到 PyPI，稍后会发布新版，你可以先按照说明从本站源码安装。

**Comment by TaoziDB** [comment]
我是这样更新的：
pip install --upgrade https://github.com/SeaHOH/ykdl/archive/master.zip

**Comment by SeaHOH** [comment]
谢谢反馈，发现个问题：当前说明中的命令无法更新到最新开发版。
正确的命令应该是：
```console
pip install https://github.com/SeaHOH/ykdl/archive/master.zip --force-reinstall --no-deps
pip install https://github.com/SeaHOH/ykdl/archive/master.zip --upgrade
```

**Comment by TaoziDB** [comment]
重新更新后，黑白直播能用了，谢谢
