### ISSUE TITLE
NameError: name 'certs' is not defined

### ISSUE THREAD

**Issue by wordlesswind** [SeaHOH/ykdl#575]
在提交前，请确保您已经检查了以下内容!

- [x] 你确实可以在浏览器或移动端中观看视频，但不能使用`ykdl`下载。
- [x] 您的`ykdl`为最新版。
- [x] 您已经阅读并按 <https://github.com/zhangn1985/ykdl/wiki> 中的指引进行了操作。
- [x] 您的问题没有在 <https://github.com/zhangn1985/ykdl/issues> 报告，否则请在原有 issue 下报告。
- [x] 本问题确实关于`ykdl`，而不是其他项目。

请将错误输出粘贴在下面:

```
ykdl
Traceback (most recent call last):
  File "C:\Users\i\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\i\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\i\AppData\Local\Programs\Python\Python39\Scripts\ykdl.exe\__main__.py", line 7, in <module>
  File "C:\Users\i\AppData\Local\Programs\Python\Python39\lib\site-packages\cykdl\__main__.py", line 154, in main
    arg_parser()
  File "C:\Users\i\AppData\Local\Programs\Python\Python39\lib\site-packages\cykdl\__main__.py", line 47, in arg_parser
    parser.add_argument('-c', '--append-certs', type=str, nargs='+', default=certs, metavar='CERTS', help="Append additional certs, used to verify SSL handshak, note that video urls can't follow this argument")
NameError: name 'certs' is not defined
```

如果您有其他附言，例如问题只在某个视频发生，或者是一般性讨论或者提出新功能，请在下面添加:

> Windows 11 OS (Build 22000.132), Python 3.9.6, pip 21.2.4, OpenSSL 1.1.1k from https://curl.se/windows/
```
pip list
Package      Version
------------ -------
bsdiff4      1.2.1 from https://www.lfd.uci.edu/~gohlke/pythonlibs/
cffi         1.14.6
cryptography 3.4.7
iso8601      0.1.14
m3u8         0.9.0
pip          21.2.4
protobuf     3.17.3
pycparser    2.20
pycryptodome 3.10.1
pyOpenSSL    20.0.1
setuptools   57.4.0
six          1.16.0
urllib3      1.26.6
wheel        0.36.2
ykdl         1.8.0a1
```

**Comment by wordlesswind** [comment]
fixed in 4729263

**Comment by SeaHOH** [comment]
已修复发布新版本，并移除 PyPI 上的 alpha 1。
