### ISSUE TITLE
ModuleNotFoundError: No module named 'ykdl.util.html'

### ISSUE THREAD

**Issue by redstoneleo** [SeaHOH/ykdl#583]
C:\Users\i>ykdl -i https://weibo.com/tv/show/1034:4693581592723516?mid=469369519
2370336
Traceback (most recent call last):
  File "c:\users\i\appdata\local\programs\python\python38\lib\runpy.py", line 19
4, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\i\appdata\local\programs\python\python38\lib\runpy.py", line 87
, in _run_code
    exec(code, run_globals)
  File "C:\Users\i\AppData\Local\Programs\Python\Python38\Scripts\ykdl.exe\__mai
n__.py", line 4, in <module>
  File "c:\users\i\appdata\local\programs\python\python38\lib\site-packages\cykd
l\__main__.py", line 27, in <module>
    from ykdl.util.html import add_default_handler, install_default_handlers
ModuleNotFoundError: No module named 'ykdl.util.html'

C:\Users\i>

**Comment by SeaHOH** [comment]
感谢反馈。之前切换分支时忘记检查了。
