### ISSUE TITLE
微博/Weibo: Sorry, current status can only be seen by login user in official client/website!

### ISSUE THREAD

**Issue by wordlesswind** [SeaHOH/ykdl#591]
在提交前，请确保您已经检查了以下内容!

- [x] 你确实可以在浏览器或移动端中观看视频，但不能使用`ykdl`下载。
- [x] 您的`ykdl`为最新版。
- [x] 您已经阅读并按 <https://github.com/SeaHOH/ykdl/wiki> 中的指引进行了操作。
- [x] 您的问题没有在 <https://github.com/SeaHOH/ykdl/issues> 报告，否则请在原有 issue 下报告。
- [x] 本问题确实关于`ykdl`或其依赖，而不是其他项目。

请将错误输出粘贴在下面:

```
ykdl --debug https://weibo.com/7503726765/LeIkpdKa2
DEBUG:ykdl.util.http:Add <urllib.request.ProxyHandler object at 0x000001A57850FCA0> to default handlers
DEBUG:ykdl.common:host> weibo.com
DEBUG:ykdl.common:short_name> weibo
DEBUG:ykdl.util.http:get_response> URL: https://weibo.com/7503726765/LeIkpdKa2
DEBUG:ykdl.util.http:Redirect to URL: https://weibo.com/sorry?pagenotfound
DEBUG:ykdl.util.http:Redirect to URL: https://passport.weibo.com/visitor/visitor?entry=miniblog&a=enter&url=https%3A%2F%2Fweibo.com%2Fsorry%3Fpagenotfound&domain=.weibo.com&ua=php-sso_sdk_client-0.6.36&_rand=1644520631.1364
DEBUG:YKDL:'NoneType' object has no attribute 'split'
Traceback (most recent call last):
  File "C:\Users\i\AppData\Local\Programs\Python\Python310\lib\site-packages\cykdl\__main__.py", line 280, in main
    info = parser(u)
  File "C:\Users\i\AppData\Local\Programs\Python\Python310\lib\site-packages\ykdl\extractor.py", line 29, in parser
    info = self.prepare()
  File "C:\Users\i\AppData\Local\Programs\Python\Python310\lib\site-packages\ykdl\extractors\weibo.py", line 41, in prepare
    streams = match1(html, 'quality_label_list=([^"]+)').split('&')[0]
AttributeError: 'NoneType' object has no attribute 'split'
```

如果您有其他附言，例如问题只在某个视频发生，或者是一般性讨论或者提出新功能，请在下面添加:

> https://weibo.com/7503726765/LeIkpdKa2

**Comment by SeaHOH** [comment]
> `Redirect to URL: https://weibo.com/sorry?pagenotfound`

好像只是被删除了？其它带视频的页面都是正常的，如 https://weibo.com/5980037952/LeS6WoRuq

**Comment by wordlesswind** [comment]
> > `Redirect to URL: https://weibo.com/sorry?pagenotfound`
> 
> 好像只是被删除了？其它带视频的页面都是正常的，如 https://weibo.com/5980037952/LeS6WoRuq

不是，只有登录后才能查看。

**Comment by SeaHOH** [comment]
看来这是更进一步的反爬保护，故意的，既然做到这种程度我们也就不再强求。本项目不会提供导入 cookies 的功能。

如果你急需下载此类视频，可以尝试通过浏览器的网络控制台或者缓存管理获取。

**Comment by hoyii** [comment]
貌似切换cookie就好了
