### ISSUE TITLE
bilibili error again

### ISSUE THREAD

**Issue by kucingkembar** [SeaHOH/ykdl#607]
sorry for my bad English, i use google translate so I tried answer based on the template

Please make sure you have checked the following before submitting!

- [checked] Your question has nothing to do with VIP content. **YKDL** will not actively support VIP content, and related questions will not be accepted.
- [checked] You can indeed play normally in browsers or mobile devices, but you cannot use **YKDL** to download.
- [checked] Your **YKDL** is the latest release version, or development version.
- [checked] You have read and followed the instructions in https://github.com/SeaHOH/ykdl/wiki.
- [i cannot read Chinese, and the google translated version may be miss the translate] Your issue is not reported in https://github.com/SeaHOH/ykdl/issues, otherwise please report it under the original issue.
- [checked] This question is really about **YKDL** or its dependencies, not other projects.

Please paste the error output below:

````
[
pip install https://github.com/SeaHOH/ykdl/archive/master.zip --upgrade
Collecting https://github.com/SeaHOH/ykdl/archive/master.zip
  Using cached https://github.com/SeaHOH/ykdl/archive/master.zip (249 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: m3u8>=1.0.0 in c:\python\python39\lib\site-packages (from ykdl==1.8.1.post1) (1.0.0)
Requirement already satisfied: jsengine>=1.0.5 in c:\python\python39\lib\site-packages (from ykdl==1.8.1.post1) (1.0.5)
Requirement already satisfied: colorama in c:\python\python39\lib\site-packages (from ykdl==1.8.1.post1) (0.4.4)
Requirement already satisfied: iso8601 in c:\python\python39\lib\site-packages (from m3u8>=1.0.0->ykdl==1.8.1.post1) (1.0.2)

ykdl -o D:\beforeAfterChinese\ -j 4 --debug -l https://www.bilibili.com/video/BV1cS4y1H7ju
)
DEBUG:ykdl.util.http:Add <urllib.request.HTTPSHandler object at 0x00000285A21A5640> to default handlers
DEBUG:ykdl.util.http:Add <urllib.request.ProxyHandler object at 0x00000285A21A5580> to default handlers
DEBUG:ykdl.common:host> www.bilibili.com
DEBUG:ykdl.common:short_name> bilibili
DEBUG:ykdl.util.http:Add <urllib.request.HTTPCookieProcessor object at 0x00000285A21A50A0> to default handlers
DEBUG:ykdl.util.http:get_response> URL: https://api.bilibili.com/x/web-interface/view?bvid=BV1cS4y1H7ju
DEBUG:ykdl.util.http:parse JSON from 'https://api.bilibili.com/x/web-interface/view?bvid=BV1cS4y1H7ju':
{"code":0,"message":"0","ttl":1,"data":{"bvid":"BV1cS4y1H7ju","aid":728146094,"videos":1,"tid":71,"tname":"综艺","copyright":2,"pic":"http://i1.hdslb.com/bfs/archive/ac641da4177769ae45c52c2f469c9d87da6f98a7.jpg","title":"【全能住宅改造王】 【简易修复版】物件046-住在店里的家","pubdate":1657118164,"ctime":1657118164,"desc":"因素材久远且质量偏低，推荐手机观看，毕竟尺寸小，用显示器看没啥必要了，糊。\n【简易修复版】【大改造!!劇的ビフォーアフター】【物件046】【店に住む家】【髙木幸 夫】【日语原版初次上映于2003年08月03日】【国兴卫视】","desc_v2":[{"raw_text":"因素材久远且质量偏低，推荐手机观看，毕竟尺寸小，用显示器看没啥必要了，糊。\n【简易修复版】【大改造!!劇的ビフォーアフター】【物件046】【店に住む家】【髙木幸夫】【 日语原版初次上映于2003年08月03日】【国兴卫视】","type":1,"biz_id":0}],"state":0,"duration":2656,"rights":{"bp":0,"elec":0,"download":1,"movie":0,"pay":0,"hd5":0,"no_reprint":0,"autoplay":1,"ugc_pay":0,"is_cooperation":0,"ugc_pay_preview":0,"no_background":0,"clean_mode":0,"is_stein_gate":0,"is_360":0,"no_share":0,"arc_pay":0,"free_watch":0},"owner":{"mid":7409049,"name":"时分Timeee","face":"http://i0.hdslb.com/bfs/face/01475e7f2a4a0aa1bda0f360fd631f4f05dbfe03.jpg"},"stat":{"aid":728146094,"view":142,"danmaku":2,"reply":0,"favorite":2,"coin":0,"share":0,"now_rank":0,"his_rank":0,"like":8,"dislike":0,"evaluation":"","argue_msg":""},"dynamic":"","cid":765710796,"dimension":{"width":960,"height":720,"rotate":0},"premiere":null,"teenage_mode":0,"is_chargeable_season":false,"no_cache":false,"pages":[{"cid":765710796,"page":1,"from":"vupload","part":"【全能住宅改造王】【简易修复版】物件046-住在店里的家","duration":2656,"vid":"","weblink":"","dimension":{"width":960,"height":720,"rotate":0},"first_frame":"http://i0.hdslb.com/bfs/storyff/n220706a22pzgeooo0fxwb2h1n1xb3gl_firsti.jpg"}],"subtitle":{"allow_submit":true,"list":[]},"is_season_display":false,"user_garb":{"url_image_ani_cut":""},"honor_reply":{}}}
DEBUG:哔哩哔哩 (Bilibili):> start at index -1
DEBUG:ykdl.util.http:get_response> URL: https://api.bilibili.com/x/web-interface/view?bvid=BV1cS4y1H7ju
DEBUG:ykdl.util.http:get_response> hit cache URL: https://api.bilibili.com/x/web-interface/view?bvid=BV1cS4y1H7ju
DEBUG:ykdl.util.http:parse JSON from 'https://api.bilibili.com/x/web-interface/view?bvid=BV1cS4y1H7ju':
{"code":0,"message":"0","ttl":1,"data":{"bvid":"BV1cS4y1H7ju","aid":728146094,"videos":1,"tid":71,"tname":"综艺","copyright":2,"pic":"http://i1.hdslb.com/bfs/archive/ac641da4177769ae45c52c2f469c9d87da6f98a7.jpg","title":"【全能住宅改造王】 【简易修复版】物件046-住在店里的家","pubdate":1657118164,"ctime":1657118164,"desc":"因素材久远且质量偏低，推荐手机观看，毕竟尺寸小，用显示器看没啥必要了，糊。\n【简易修复版】【大改造!!劇的ビフォーアフター】【物件046】【店に住む家】【髙木幸 夫】【日语原版初次上映于2003年08月03日】【国兴卫视】","desc_v2":[{"raw_text":"因素材久远且质量偏低，推荐手机观看，毕竟尺寸小，用显示器看没啥必要了，糊。\n【简易修复版】【大改造!!劇的ビフォーアフター】【物件046】【店に住む家】【髙木幸夫】【 日语原版初次上映于2003年08月03日】【国兴卫视】","type":1,"biz_id":0}],"state":0,"duration":2656,"rights":{"bp":0,"elec":0,"download":1,"movie":0,"pay":0,"hd5":0,"no_reprint":0,"autoplay":1,"ugc_pay":0,"is_cooperation":0,"ugc_pay_preview":0,"no_background":0,"clean_mode":0,"is_stein_gate":0,"is_360":0,"no_share":0,"arc_pay":0,"free_watch":0},"owner":{"mid":7409049,"name":"时分Timeee","face":"http://i0.hdslb.com/bfs/face/01475e7f2a4a0aa1bda0f360fd631f4f05dbfe03.jpg"},"stat":{"aid":728146094,"view":142,"danmaku":2,"reply":0,"favorite":2,"coin":0,"share":0,"now_rank":0,"his_rank":0,"like":8,"dislike":0,"evaluation":"","argue_msg":""},"dynamic":"","cid":765710796,"dimension":{"width":960,"height":720,"rotate":0},"premiere":null,"teenage_mode":0,"is_chargeable_season":false,"no_cache":false,"pages":[{"cid":765710796,"page":1,"from":"vupload","part":"【全能住宅改造王】【简易修复版】物件046-住在店里的家","duration":2656,"vid":"","weblink":"","dimension":{"width":960,"height":720,"rotate":0},"first_frame":"http://i0.hdslb.com/bfs/storyff/n220706a22pzgeooo0fxwb2h1n1xb3gl_firsti.jpg"}],"subtitle":{"allow_submit":true,"list":[]},"is_season_display":false,"user_garb":{"url_image_ani_cut":""},"honor_reply":{}}}
DEBUG:ykdl.util.http:get_response> URL: https://www.bilibili.com/video/BV1cS4y1H7ju?p=1
DEBUG:ykdl.util.http:get_response> URL: https://interface.bilibili.com/v2/playurl?appkey=iVGUTjsxvpLeuDCf&cid=765710796&platform=html5&player=0&qn=0&sign=e51335b9c5e864664fb410f97272fa3e
DEBUG:ykdl.util.http:parse XML from 'https://interface.bilibili.com/v2/playurl?appkey=iVGUTjsxvpLeuDCf&cid=765710796&platform=html5&player=0&qn=0&sign=e51335b9c5e864664fb410f97272fa3e':
<?xml version="1.0" encoding="UTF-8"?>
<video>
   <result>suee</result>
   <timelength>2655119</timelength>
   <format>flv480</format>
   <quality><![CDATA[32]]></quality>
   <accept_format><![CDATA[flv720,flv480,mp4]]></accept_format>
   <accept_description><![CDATA[高清 720P,清晰 480P,流畅 360P]]></accept_description>
   <accept_quality><![CDATA[64,32,16]]></accept_quality>
   <video_codecid><![CDATA[7]]></video_codecid>
   <video_project><![CDATA[true]]></video_project>
   <from><![CDATA[local]]></from>
   <seek_param><![CDATA[start]]></seek_param>
   <seek_type><![CDATA[offset]]></seek_type>
   <durl>
      <order>1</order>
      <length>2655119</length>
      <size>182635991</size>
      <url><![CDATA[http://upos-hz-mirrorakam.akamaized.net/upgcxcode/96/07/765710796/765710796-1-32.flv?e=ig8euxZM2rNcNbRahwdVhoM17zdVhwdEto8g5X10ugNcXBB_&deadline=1657199423&gen=playurl&nbs=1&oi=608702096&os=akam&platform=html5&trid=23d807003b724159a9b1919799b444fd&uipk=5&upsig=99e69ce9e434ac4d417d507ffa1631d1&uparams=e,deadline,gen,nbs,oi,os,platform,trid,uipk&hdnts=exp=1657199423~hmac=8d63593897dd83af97825fc6c0419bd246cf5353e8e9d07e42db6a37df4a216f&mid=0]]></url>
   </durl>
</video>
DEBUG:ykdl.util.http:get_response> URL: https://interface.bilibili.com/v2/playurl?appkey=iVGUTjsxvpLeuDCf&cid=765710796&platform=html5&player=0&qn=64&sign=fd7b20effea6efad61e5570b0c4ab06e
DEBUG:ykdl.util.http:parse XML from 'https://interface.bilibili.com/v2/playurl?appkey=iVGUTjsxvpLeuDCf&cid=765710796&platform=html5&player=0&qn=64&sign=fd7b20effea6efad61e5570b0c4ab06e':
<?xml version="1.0" encoding="UTF-8"?>
<video>
   <result>suee</result>
   <timelength>2655119</timelength>
   <format>flv720</format>
   <quality><![CDATA[64]]></quality>
   <accept_format><![CDATA[flv720,flv480,mp4]]></accept_format>
   <accept_description><![CDATA[高清 720P,清晰 480P,流畅 360P]]></accept_description>
   <accept_quality><![CDATA[64,32,16]]></accept_quality>
   <video_codecid><![CDATA[7]]></video_codecid>
   <video_project><![CDATA[true]]></video_project>
   <from><![CDATA[local]]></from>
   <seek_param><![CDATA[start]]></seek_param>
   <seek_type><![CDATA[offset]]></seek_type>
   <durl>
      <order>1</order>
      <length>2655119</length>
      <size>338837577</size>
      <url><![CDATA[http://upos-hz-mirrorakam.akamaized.net/upgcxcode/96/07/765710796/765710796-1-64.flv?e=ig8euxZM2rNcNbh17zUVhoMzhWuBhwdEto8g5X10ugNcXBB_&deadline=1657199424&gen=playurl&nbs=1&oi=608702096&os=akam&platform=html5&trid=7f8b76f370c343099dfb20af092a83fb&uipk=5&upsig=691541a4a8c4887e675946cba2ddce61&uparams=e,deadline,gen,nbs,oi,os,platform,trid,uipk&hdnts=exp=1657199424~hmac=903f17cab874d8114b62e66158cad6a1803c9080ea9c4c2d41a6ac893cff8adc&mid=0]]></url>
   </durl>
</video>
DEBUG:ykdl.util.http:get_response> URL: https://interface.bilibili.com/v2/playurl?appkey=iVGUTjsxvpLeuDCf&cid=765710796&platform=html5&player=0&qn=16&sign=3214a0a82408ed1ffb5bf56c06e76cb0
DEBUG:ykdl.util.http:parse XML from 'https://interface.bilibili.com/v2/playurl?appkey=iVGUTjsxvpLeuDCf&cid=765710796&platform=html5&player=0&qn=16&sign=3214a0a82408ed1ffb5bf56c06e76cb0':
<?xml version="1.0" encoding="UTF-8"?>
<video>
   <result>suee</result>
   <timelength>2655040</timelength>
   <format>mp4</format>
   <quality><![CDATA[16]]></quality>
   <accept_format><![CDATA[flv720,flv480,mp4]]></accept_format>
   <accept_description><![CDATA[高清 720P,清晰 480P,流畅 360P]]></accept_description>
   <accept_quality><![CDATA[64,32,16]]></accept_quality>
   <video_codecid><![CDATA[7]]></video_codecid>
   <video_project><![CDATA[true]]></video_project>
   <from><![CDATA[local]]></from>
   <seek_param><![CDATA[start]]></seek_param>
   <seek_type><![CDATA[second]]></seek_type>
   <durl>
      <order>1</order>
      <length>2655040</length>
      <size>117231444</size>
      <url><![CDATA[http://upos-hz-mirrorakam.akamaized.net/upgcxcode/96/07/765710796/765710796-1-16.mp4?e=ig8euxZM2rNcNbR1hwdVhoM1hWdVhwdEto8g5X10ugNcXBB_&deadline=1657199424&gen=playurl&nbs=1&oi=608702096&os=akam&platform=html5&trid=26497f326bf0407fa2cefa3028eb6820&uipk=5&upsig=02832a599a8997428375bc17d4697f2c&uparams=e,deadline,gen,nbs,oi,os,platform,trid,uipk&hdnts=exp=1657199424~hmac=5356a076ec51dae8fcb9180381d0dea11e1cec881c5f5d2a6d5f9015b6a0e23b&mid=0]]></url>
   </durl>
</video>
site:                 哔哩哔哩 (Bilibili)
title:                【全能住宅改造王】【简易修复版】物件046-住在店里的家
artist:               时分Timeee
streams:
    - format:         TD TD-64
      container:      flv
      video-profile:  高清 720P
      size:           323.141 MiB (338837577 Bytes)
    # download-with:  ykdl --format=TD-64 [URL]

Start downloading: 【全能住宅改造王】【简易修复版】物件046-住在店里的家_时分Timeee_TD-64
Restored: file part 0 is incomplete at 0%
Restored: file part 0 is incomplete at 0%
Restored: file part 0 is incomplete at 0%
DEBUG:YKDL:timed out                                                                        0% [0/1] [00:05:13]
Traceback (most recent call last):
  File "C:\Python\Python39\lib\site-packages\cykdl\__main__.py", line 316, in main
    for rc in map(handle_video, args.video_urls):
  File "C:\Python\Python39\lib\site-packages\cykdl\__main__.py", line 228, in handle_video
    handle_videoinfo(i)
  File "C:\Python\Python39\lib\site-packages\cykdl\__main__.py", line 211, in handle_videoinfo
    download(urls, name, ext, live)
  File "C:\Python\Python39\lib\site-packages\cykdl\__main__.py", line 109, in download
    if save_urls(urls, name, ext, jobs=args.jobs,
  File "C:\Python\Python39\lib\site-packages\ykdl\util\download.py", line 327, in save_urls
    save_url(urls[0], name, ext, status, reporthook=reporthook)
  File "C:\Python\Python39\lib\site-packages\ykdl\util\download.py", line 282, in save_url
    raise e
  File "C:\Python\Python39\lib\site-packages\ykdl\util\download.py", line 278, in save_url
    if _save_url(*args, **kwargs):
  File "C:\Python\Python39\lib\site-packages\ykdl\util\download.py", line 257, in _save_url
    block = response.read(bs)
  File "C:\Python\Python39\lib\http\client.py", line 463, in read
    n = self.readinto(b)
  File "C:\Python\Python39\lib\http\client.py", line 507, in readinto
    n = self.fp.readinto(b)
  File "C:\Python\Python39\lib\socket.py", line 704, in readinto
    return self._sock.recv_into(b)
socket.timeout: timed out
]
````

If you have other postscripts, such as the question only occurs in a certain video, or a general discussion or a suggestion for a new feature, please add it below:
````
[
i do not touch this software may be 2 months or more, when I try this software again today, that problem occurred,
thank you have a nice day
]
````

Edit : after try 5 times the program work again

**Comment by SeaHOH** [comment]
Problem of CDN.
