### ISSUE TITLE
抖音直播不能看（但是世界杯能看）

### ISSUE THREAD

**Issue by CJN1986** [SeaHOH/ykdl#617]
在提交前，请确保您已经检查了以下内容!

- [x] 你的问题无关 VIP 内容。**YKDL** 不会主动支持 VIP 内容，相关问题一概不予受理。
- [x] 你确实可以在浏览器或移动端中正常播放，但不能使用 **YKDL** 下载。
- [x] 你的 **YKDL** 为最新发布版本，或开发版本。
- [x] 你已经阅读并按 https://github.com/SeaHOH/ykdl/wiki 中的指引进行了操作。
- [x] 你的问题没有在 https://github.com/SeaHOH/ykdl/issues 报告，否则请在原有 issue 下报告。
- [x] 本问题确实关于 **YKDL** 或其依赖，而不是其他项目。

请将错误输出粘贴在下面:

```
ykdl https://live.douyin.com/948452105030 -p mpv.exe --debug

DEBUG:ykdl.util.http:Add <urllib.request.ProxyHandler object at 0x000000881855F6D0> to default handlers
DEBUG:ykdl.common:host> live.douyin.com
DEBUG:ykdl.common:short_name> douyin
DEBUG:ykdl.util.http:get_response> URL: https://live.douyin.com/webcast/web/enter/?aid=6383&live_id=1&device_platform=we
b&web_rid=948452105030
DEBUG:ykdl.util.http:parse JSON from 'https://live.douyin.com/webcast/web/enter/?aid=6383&live_id=1&device_platform=web&
web_rid=948452105030':
{"data":{"message":"系统繁忙，请稍后再试","prompts":"系统繁忙，请稍后再试"},"extra":{"now":1669477656895},"status_code":
10037}
DEBUG:YKDL:'data'
Traceback (most recent call last):
  File "C:\Users\Usee\AppData\Roaming\Python\Python39\site-packages\cykdl\__main__.py", line 318, in main
    for rc in map(handle_video, args.video_urls):
  File "C:\Users\Usee\AppData\Roaming\Python\Python39\site-packages\cykdl\__main__.py", line 227, in handle_video
    info = parser(u)
  File "C:\Users\Usee\AppData\Roaming\Python\Python39\site-packages\ykdl\extractor.py", line 44, in parser
    info = self.prepare()
  File "C:\Users\Usee\AppData\Roaming\Python\Python39\site-packages\ykdl\extractors\douyin\live.py", line 29, in prepare

    video_info = data['data']['data'][0]
KeyError: 'data'
```

如果你有其他附言，例如问题只在某个视频发生，或者是一般性讨论或者提出新功能，请在下面添加:

YKDL 版本：1.8.2.dev

**Comment by SeaHOH** [comment]
b9f558ff533a3a4b9ce0852ef05b4660b7fb1226 已撤回
好像今天 API 改了，然后我昨天测试是对的。

**Comment by CJN1986** [comment]
现在正常了。
