### ISSUE TITLE
Python 3.10 windows compability problem

### ISSUE THREAD

**Issue by wnpllrzodiac** [SeaHOH/ykdl#625]
在提交前，请确保您已经检查了以下内容!

- [ ] 你的问题无关 VIP 内容。**YKDL** 不会主动支持 VIP 内容，相关问题一概不予受理。
- [ ] 你确实可以在浏览器或移动端中正常播放，但不能使用 **YKDL** 下载。
- [ ] 你的 **YKDL** 为最新发布版本，或开发版本。
- [ ] 你已经阅读并按 https://github.com/SeaHOH/ykdl/wiki 中的指引进行了操作。
- [ ] 你的问题没有在 https://github.com/SeaHOH/ykdl/issues 报告，否则请在原有 issue 下报告。
- [ ] 本问题确实关于 **YKDL** 或其依赖，而不是其他项目。

请将错误输出粘贴在下面:
ykdl-1.8.1.post1

```
D:\Archive\drawing\haha>ykdl "https://www.bilibili.com/video/BV1Nk4y117ac?p=16"
Traceback (most recent call last):
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python310-32\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python310-32\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python310-32\Scripts\ykdl.exe\__main__.py", line 4, in <module>
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python310-32\lib\site-packages\cykdl\__main__.py", line 28, in <module>
    from ykdl.util.m3u8 import live_m3u8, crypto_m3u8, load_m3u8, _load as _load_m3u8
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python310-32\lib\site-packages\ykdl\util\m3u8.py", line 25, in <module>
    from m3u8.parser import urljoin
ImportError: cannot import name 'urljoin' from 'm3u8.parser' (C:\Users\xxx\AppData\Local\Programs\Python\Python310-32\lib\site-packages\m3u8\parser.py)
```

如果你有其他附言，例如问题只在某个视频发生，或者是一般性讨论或者提出新功能，请在下面添加:

[在这里输入内容文本]

**Comment by SeaHOH** [comment]
1.8.2 已释出，请更新。
