### ISSUE TITLE
bilibili 直播错误

### ISSUE THREAD

**Issue by zizhengwu** [SeaHOH/ykdl#631]
请将错误输出粘贴在下面:

```
❯ ykdl https://live.bilibili.com/888 --debug -p mpv
DEBUG:ykdl.util.http:Add <urllib.request.ProxyHandler object at 0x10dc16cb0> to default handlers
DEBUG:ykdl.common:host> live.bilibili.com
DEBUG:ykdl.common:short_name> bilibili
DEBUG:ykdl.util.http:Add <urllib.request.HTTPCookieProcessor object at 0x10e8c8100> to default handlers
DEBUG:Bilibili live (哔哩哔哩直播):media ID: ('888',)
DEBUG:ykdl.util.http:get_response> URL: https://api.live.bilibili.com/room/v1/Room/room_init?id=888
DEBUG:ykdl.util.http:parse JSON from 'https://api.live.bilibili.com/room/v1/Room/room_init?id=888':
{"code":0,"msg":"ok","message":"ok","data":{"room_id":7685334,"short_id":888,"uid":3117396,"need_p2p":0,"is_hidden":false,"is_locked":false,"is_portrait":false,"live_status":1,"hidden_till":0,"lock_till":0,"encrypted":false,"pwd_verified":false,"live_time":1698422551,"room_shield":1,"is_sp":0,"special_type":0}}
DEBUG:Bilibili live (哔哩哔哩直播):media ID: ('888', 7685334, '3117396')
DEBUG:ykdl.util.http:get_response> URL: https://api.live.bilibili.com/room/v1/Room/get_status_info_by_uids?uids%5B%5D=3117396
DEBUG:ykdl.util.http:parse JSON from 'https://api.live.bilibili.com/room/v1/Room/get_status_info_by_uids?uids%5B%5D=3117396':
{"code":0,"msg":"success","message":"success","data":{"3117396":{"title":"GG 2-0 NOUNS","room_id":7685334,"uid":3117396,"online":395027,"live_time":1698422551,"live_status":1,"short_id":888,"area":4,"area_name":"电子竞技","area_v2_id":92,"area_v2_name":"DOTA2","area_v2_parent_name":"网游","area_v2_parent_id":2,"uname":"狡兔者DC","face":"https://i0.hdslb.com/bfs/face/8c12fbd18cf3190df1e6db31628d61204319104e.jpg","tag_name":"英雄联盟,DOTA2,星际争霸2,CSGO,风暴英雄","tags":"DOTA2,FGO,真实肥宅,诚信官托","cover_from_user":"https://i0.hdslb.com/bfs/live/d2b31ee34439e70901726ebffb356a22083cb855.jpg","keyframe":"https://i0.hdslb.com/bfs/live-key-frame/keyframe10280325000007685334oxukdm.jpg","lock_till":"0000-00-00 00:00:00","hidden_till":"0000-00-00 00:00:00","broadcast_type":0}}}
DEBUG:ykdl.util.http:get_response> URL: https://api.live.bilibili.com/xlive/web-room/v2/index/getRoomPlayInfo?room_id=7685334&protocol=0%2C1&format=0%2C1%2C2&codec=0%2C1&qn=1&platform=web&ptype=8&dolby=5
DEBUG:ykdl.util.http:parse JSON from 'https://api.live.bilibili.com/xlive/web-room/v2/index/getRoomPlayInfo?room_id=7685334&protocol=0%2C1&format=0%2C1%2C2&codec=0%2C1&qn=1&platform=web&ptype=8&dolby=5':
{"code":0,"message":"0","ttl":1,"data":{"room_id":7685334,"short_id":888,"uid":3117396,"is_hidden":false,"is_locked":false,"is_portrait":false,"live_status":1,"hidden_till":0,"lock_till":0,"encrypted":false,"pwd_verified":true,"live_time":1698422551,"room_shield":1,"all_special_types":[],"playurl_info":{"conf_json":"{\"cdn_rate\":10000,\"report_interval_sec\":150}","playurl":{"cid":7685334,"g_qn_desc":[{"qn":30000,"desc":"杜比","hdr_desc":"","attr_desc":null},{"qn":20000,"desc":"4K","hdr_desc":"","attr_desc":null},{"qn":10000,"desc":"原画","hdr_desc":"","attr_desc":null},{"qn":400,"desc":"蓝光","hdr_desc":"HDR","attr_desc":null},{"qn":250,"desc":"超清","hdr_desc":"HDR","attr_desc":null},{"qn":150,"desc":"高清","hdr_desc":"","attr_desc":null},{"qn":80,"desc":"流畅","hdr_desc":"","attr_desc":null}],"stream":[{"protocol_name":"http_stream","format":[{"format_name":"flv","codec":[{"codec_name":"avc","current_qn":150,"accept_qn":[10000,400,250,150],"base_url":"/live-bvc/904692/live_3117396_4657598_1500.flv?","url_info":[{"host":"https://d1--ov-gotcha07.bilivideo.com","extra":"expires=1698438666\u0026len=0\u0026oi=2283289789\u0026pt=web\u0026qn=0\u0026trid=1000187847b25c8d4c38adf8d289c95e1c33\u0026sigparams=cdn,expires,len,oi,pt,qn,trid\u0026cdn=ov-gotcha07\u0026sign=25db9248d0daf8374f4d596d68325f4d\u0026sk=1304f646dfeb4df8b6e7ff33c167d3adda26bb4da5f21f1459ebf5b3c7780c72\u0026p2p_type=0\u0026sl=10\u0026free_type=0\u0026mid=0\u0026pp=rtmp\u0026source=onetier\u0026trace=0\u0026site=0b4f7fe678dbac0b85e764e1b3e24cc4\u0026order=1","stream_ttl":3600},{"host":"https://d1--ov-gotcha05.bilivideo.com","extra":"expires=1698438666\u0026len=0\u0026oi=2283289789\u0026pt=web\u0026qn=0\u0026trid=1000187847b25c8d4c38adf8d289c95e1c33\u0026sigparams=cdn,expires,len,oi,pt,qn,trid\u0026cdn=ov-gotcha05\u0026sign=109c0aaa1aabce35ba517d264f9eb23b\u0026sk=1304f646dfeb4df8b6e7ff33c167d3adda26bb4da5f21f1459ebf5b3c7780c72\u0026p2p_type=0\u0026sl=10\u0026free_type=0\u0026mid=0\u0026pp=rtmp\u0026source=onetier\u0026trace=0\u0026site=0b4f7fe678dbac0b85e764e1b3e24cc4\u0026order=2","stream_ttl":3600}],"hdr_qn":null,"dolby_type":0,"attr_name":""},{"codec_name":"hevc","current_qn":250,"accept_qn":[10000,250],"base_url":"/live-bvc/904692/live_3117396_4657598_minihevc.flv?","url_info":[{"host":"https://d1--ov-gotcha07.bilivideo.com","extra":"expires=1698438666\u0026len=0\u0026oi=2283289789\u0026pt=web\u0026qn=0\u0026trid=1000187847b25c8d4c38adf8d289c95e1c33\u0026sigparams=cdn,expires,len,oi,pt,qn,trid\u0026cdn=ov-gotcha07\u0026sign=5f30e6809d320e759fd03695299bef8a\u0026sk=1304f646dfeb4df8b6e7ff33c167d3adda26bb4da5f21f1459ebf5b3c7780c72\u0026p2p_type=0\u0026sl=10\u0026free_type=0\u0026mid=0\u0026pp=rtmp\u0026source=onetier\u0026trace=0\u0026site=0b4f7fe678dbac0b85e764e1b3e24cc4\u0026order=1","stream_ttl":3600},{"host":"https://d1--ov-gotcha05.bilivideo.com","extra":"expires=1698438666\u0026len=0\u0026oi=2283289789\u0026pt=web\u0026qn=0\u0026trid=1000187847b25c8d4c38adf8d289c95e1c33\u0026sigparams=cdn,expires,len,oi,pt,qn,trid\u0026cdn=ov-gotcha05\u0026sign=b7b4dca6740f76b5a5f9a5855c5b6756\u0026sk=1304f646dfeb4df8b6e7ff33c167d3adda26bb4da5f21f1459ebf5b3c7780c72\u0026p2p_type=0\u0026sl=10\u0026free_type=0\u0026mid=0\u0026pp=rtmp\u0026source=onetier\u0026trace=0\u0026site=0b4f7fe678dbac0b85e764e1b3e24cc4\u0026order=2","stream_ttl":3600}],"hdr_qn":null,"dolby_type":0,"attr_name":""}]}]},{"protocol_name":"http_hls","format":[{"format_name":"ts","codec":[{"codec_name":"avc","current_qn":150,"accept_qn":[10000,400,250,150],"base_url":"/live-bvc/904692/live_3117396_4657598_1500.m3u8?","url_info":[{"host":"https://d1--ov-gotcha105.bilivideo.com","extra":"expires=1698438666\u0026len=0\u0026oi=2283289789\u0026pt=web\u0026qn=0\u0026trid=1003187847b25c8d4c38adf8d289c95e1c33\u0026sigparams=cdn,expires,len,oi,pt,qn,trid\u0026cdn=ov-gotcha105\u0026sign=e918ac888fd9c670575fafa93a1b0031\u0026sk=1304f646dfeb4df8b6e7ff33c167d3adda26bb4da5f21f1459ebf5b3c7780c72\u0026p2p_type=0\u0026sl=10\u0026free_type=0\u0026mid=0\u0026pp=rtmp\u0026source=onetier\u0026trace=0\u0026site=0b4f7fe678dbac0b85e764e1b3e24cc4\u0026order=1","stream_ttl":3600}],"hdr_qn":null,"dolby_type":0,"attr_name":""}]}]}],"p2p_data":{"p2p":false,"p2p_type":0,"m_p2p":false,"m_servers":null},"dolby_qn":null}},"official_type":0,"official_room_id":0}}
DEBUG:ykdl.util.http:get_response> URL: https://api.live.bilibili.com/xlive/web-room/v2/index/getRoomPlayInfo?room_id=7685334&protocol=0%2C1&format=0%2C1%2C2&codec=0%2C1&qn=10000&platform=web&ptype=8&dolby=5
DEBUG:ykdl.util.http:parse JSON from 'https://api.live.bilibili.com/xlive/web-room/v2/index/getRoomPlayInfo?room_id=7685334&protocol=0%2C1&format=0%2C1%2C2&codec=0%2C1&qn=10000&platform=web&ptype=8&dolby=5':
{"code":0,"message":"0","ttl":1,"data":{"room_id":7685334,"short_id":888,"uid":3117396,"is_hidden":false,"is_locked":false,"is_portrait":false,"live_status":1,"hidden_till":0,"lock_till":0,"encrypted":false,"pwd_verified":true,"live_time":1698422551,"room_shield":1,"all_special_types":[],"playurl_info":{"conf_json":"{\"cdn_rate\":10000,\"report_interval_sec\":150}","playurl":{"cid":7685334,"g_qn_desc":[{"qn":30000,"desc":"杜比","hdr_desc":"","attr_desc":null},{"qn":20000,"desc":"4K","hdr_desc":"","attr_desc":null},{"qn":10000,"desc":"原画","hdr_desc":"","attr_desc":null},{"qn":400,"desc":"蓝光","hdr_desc":"HDR","attr_desc":null},{"qn":250,"desc":"超清","hdr_desc":"HDR","attr_desc":null},{"qn":150,"desc":"高清","hdr_desc":"","attr_desc":null},{"qn":80,"desc":"流畅","hdr_desc":"","attr_desc":null}],"stream":[{"protocol_name":"http_stream","format":[{"format_name":"flv","codec":[{"codec_name":"avc","current_qn":150,"accept_qn":[10000,400,250,150],"base_url":"/live-bvc/290047/live_3117396_4657598_1500.flv?","url_info":[{"host":"https://d1--ov-gotcha07.bilivideo.com","extra":"expires=1698438667\u0026len=0\u0026oi=2283289789\u0026pt=web\u0026qn=0\u0026trid=10007c681379da5047ea9a1745453cab7f52\u0026sigparams=cdn,expires,len,oi,pt,qn,trid\u0026cdn=ov-gotcha07\u0026sign=2a1fa554fc0576da705bbd20bb3079a2\u0026sk=1304f646dfeb4df8b6e7ff33c167d3adda26bb4da5f21f1459ebf5b3c7780c72\u0026p2p_type=0\u0026sl=9\u0026free_type=0\u0026mid=0\u0026pp=rtmp\u0026source=onetier\u0026trace=0\u0026site=3fa9f3713b55c3df54c282427b025191\u0026order=1","stream_ttl":3600},{"host":"https://d1--ov-gotcha05.bilivideo.com","extra":"expires=1698438667\u0026len=0\u0026oi=2283289789\u0026pt=web\u0026qn=0\u0026trid=10007c681379da5047ea9a1745453cab7f52\u0026sigparams=cdn,expires,len,oi,pt,qn,trid\u0026cdn=ov-gotcha05\u0026sign=4d057acdb1b2a2cc16c65823cf1a45d9\u0026sk=1304f646dfeb4df8b6e7ff33c167d3adda26bb4da5f21f1459ebf5b3c7780c72\u0026p2p_type=0\u0026sl=9\u0026free_type=0\u0026mid=0\u0026pp=rtmp\u0026source=onetier\u0026trace=0\u0026site=3fa9f3713b55c3df54c282427b025191\u0026order=2","stream_ttl":3600}],"hdr_qn":null,"dolby_type":0,"attr_name":""},{"codec_name":"hevc","current_qn":250,"accept_qn":[10000,250],"base_url":"/live-bvc/290047/live_3117396_4657598_minihevc.flv?","url_info":[{"host":"https://d1--ov-gotcha07.bilivideo.com","extra":"expires=1698438667\u0026len=0\u0026oi=2283289789\u0026pt=web\u0026qn=0\u0026trid=10007c681379da5047ea9a1745453cab7f52\u0026sigparams=cdn,expires,len,oi,pt,qn,trid\u0026cdn=ov-gotcha07\u0026sign=75d81e8def3c4ba1f770fdb9a17c55e4\u0026sk=1304f646dfeb4df8b6e7ff33c167d3adda26bb4da5f21f1459ebf5b3c7780c72\u0026p2p_type=0\u0026sl=9\u0026free_type=0\u0026mid=0\u0026pp=rtmp\u0026source=onetier\u0026trace=0\u0026site=3fa9f3713b55c3df54c282427b025191\u0026order=1","stream_ttl":3600},{"host":"https://d1--ov-gotcha05.bilivideo.com","extra":"expires=1698438667\u0026len=0\u0026oi=2283289789\u0026pt=web\u0026qn=0\u0026trid=10007c681379da5047ea9a1745453cab7f52\u0026sigparams=cdn,expires,len,oi,pt,qn,trid\u0026cdn=ov-gotcha05\u0026sign=54b6ffc4d27d015aae5143284415deb5\u0026sk=1304f646dfeb4df8b6e7ff33c167d3adda26bb4da5f21f1459ebf5b3c7780c72\u0026p2p_type=0\u0026sl=9\u0026free_type=0\u0026mid=0\u0026pp=rtmp\u0026source=onetier\u0026trace=0\u0026site=3fa9f3713b55c3df54c282427b025191\u0026order=2","stream_ttl":3600}],"hdr_qn":null,"dolby_type":0,"attr_name":""}]}]},{"protocol_name":"http_hls","format":[{"format_name":"ts","codec":[{"codec_name":"avc","current_qn":150,"accept_qn":[10000,400,250,150],"base_url":"/live-bvc/290047/live_3117396_4657598_1500.m3u8?","url_info":[{"host":"https://d1--ov-gotcha105.bilivideo.com","extra":"expires=1698438667\u0026len=0\u0026oi=2283289789\u0026pt=web\u0026qn=0\u0026trid=10037c681379da5047ea9a1745453cab7f52\u0026sigparams=cdn,expires,len,oi,pt,qn,trid\u0026cdn=ov-gotcha105\u0026sign=da34aeecfe8c2c8ae65dfc19a35fd103\u0026sk=1304f646dfeb4df8b6e7ff33c167d3adda26bb4da5f21f1459ebf5b3c7780c72\u0026p2p_type=0\u0026sl=9\u0026free_type=0\u0026mid=0\u0026pp=rtmp\u0026source=onetier\u0026trace=0\u0026site=3fa9f3713b55c3df54c282427b025191\u0026order=1","stream_ttl":3600}],"hdr_qn":null,"dolby_type":0,"attr_name":""}]}]}],"p2p_data":{"p2p":false,"p2p_type":0,"m_p2p":false,"m_servers":null},"dolby_qn":null}},"official_type":0,"official_room_id":0}}
DEBUG:ykdl.util.http:get_response> URL: https://api.live.bilibili.com/xlive/web-room/v2/index/getRoomPlayInfo?room_id=7685334&protocol=0%2C1&format=0%2C1%2C2&codec=0%2C1&qn=250&platform=web&ptype=8&dolby=5
DEBUG:ykdl.util.http:parse JSON from 'https://api.live.bilibili.com/xlive/web-room/v2/index/getRoomPlayInfo?room_id=7685334&protocol=0%2C1&format=0%2C1%2C2&codec=0%2C1&qn=250&platform=web&ptype=8&dolby=5':
{"code":0,"message":"0","ttl":1,"data":{"room_id":7685334,"short_id":888,"uid":3117396,"is_hidden":false,"is_locked":false,"is_portrait":false,"live_status":1,"hidden_till":0,"lock_till":0,"encrypted":false,"pwd_verified":true,"live_time":1698422551,"room_shield":1,"all_special_types":[],"playurl_info":{"conf_json":"{\"cdn_rate\":10000,\"report_interval_sec\":150}","playurl":{"cid":7685334,"g_qn_desc":[{"qn":30000,"desc":"杜比","hdr_desc":"","attr_desc":null},{"qn":20000,"desc":"4K","hdr_desc":"","attr_desc":null},{"qn":10000,"desc":"原画","hdr_desc":"","attr_desc":null},{"qn":400,"desc":"蓝光","hdr_desc":"HDR","attr_desc":null},{"qn":250,"desc":"超清","hdr_desc":"HDR","attr_desc":null},{"qn":150,"desc":"高清","hdr_desc":"","attr_desc":null},{"qn":80,"desc":"流畅","hdr_desc":"","attr_desc":null}],"stream":[{"protocol_name":"http_stream","format":[{"format_name":"flv","codec":[{"codec_name":"avc","current_qn":150,"accept_qn":[10000,400,250,150],"base_url":"/live-bvc/480055/live_3117396_4657598_1500.flv?","url_info":[{"host":"https://d1--ov-gotcha07.bilivideo.com","extra":"expires=1698438667\u0026len=0\u0026oi=2283289789\u0026pt=web\u0026qn=0\u0026trid=10004866ef499f244853847fd6940f281c4f\u0026sigparams=cdn,expires,len,oi,pt,qn,trid\u0026cdn=ov-gotcha07\u0026sign=09aee30d919e10fb3c39e8a24198e8f9\u0026sk=1304f646dfeb4df8b6e7ff33c167d3adda26bb4da5f21f1459ebf5b3c7780c72\u0026p2p_type=0\u0026sl=9\u0026free_type=0\u0026mid=0\u0026pp=rtmp\u0026source=onetier\u0026trace=0\u0026site=3fa9f3713b55c3df54c282427b025191\u0026order=1","stream_ttl":3600},{"host":"https://d1--ov-gotcha05.bilivideo.com","extra":"expires=1698438667\u0026len=0\u0026oi=2283289789\u0026pt=web\u0026qn=0\u0026trid=10004866ef499f244853847fd6940f281c4f\u0026sigparams=cdn,expires,len,oi,pt,qn,trid\u0026cdn=ov-gotcha05\u0026sign=a0b2a844ec472b6245c842978634a772\u0026sk=1304f646dfeb4df8b6e7ff33c167d3adda26bb4da5f21f1459ebf5b3c7780c72\u0026p2p_type=0\u0026sl=9\u0026free_type=0\u0026mid=0\u0026pp=rtmp\u0026source=onetier\u0026trace=0\u0026site=3fa9f3713b55c3df54c282427b025191\u0026order=2","stream_ttl":3600}],"hdr_qn":null,"dolby_type":0,"attr_name":""},{"codec_name":"hevc","current_qn":250,"accept_qn":[10000,250],"base_url":"/live-bvc/480055/live_3117396_4657598_minihevc.flv?","url_info":[{"host":"https://d1--ov-gotcha07.bilivideo.com","extra":"expires=1698438667\u0026len=0\u0026oi=2283289789\u0026pt=web\u0026qn=0\u0026trid=10004866ef499f244853847fd6940f281c4f\u0026sigparams=cdn,expires,len,oi,pt,qn,trid\u0026cdn=ov-gotcha07\u0026sign=9faa9bc00e491d53f545db7ad00f8755\u0026sk=1304f646dfeb4df8b6e7ff33c167d3adda26bb4da5f21f1459ebf5b3c7780c72\u0026p2p_type=0\u0026sl=9\u0026free_type=0\u0026mid=0\u0026pp=rtmp\u0026source=onetier\u0026trace=0\u0026site=3fa9f3713b55c3df54c282427b025191\u0026order=1","stream_ttl":3600},{"host":"https://d1--ov-gotcha05.bilivideo.com","extra":"expires=1698438667\u0026len=0\u0026oi=2283289789\u0026pt=web\u0026qn=0\u0026trid=10004866ef499f244853847fd6940f281c4f\u0026sigparams=cdn,expires,len,oi,pt,qn,trid\u0026cdn=ov-gotcha05\u0026sign=8dd7c26fb7d749f3ebadb1fddc1918d2\u0026sk=1304f646dfeb4df8b6e7ff33c167d3adda26bb4da5f21f1459ebf5b3c7780c72\u0026p2p_type=0\u0026sl=9\u0026free_type=0\u0026mid=0\u0026pp=rtmp\u0026source=onetier\u0026trace=0\u0026site=3fa9f3713b55c3df54c282427b025191\u0026order=2","stream_ttl":3600}],"hdr_qn":null,"dolby_type":0,"attr_name":""}]}]},{"protocol_name":"http_hls","format":[{"format_name":"ts","codec":[{"codec_name":"avc","current_qn":150,"accept_qn":[10000,400,250,150],"base_url":"/live-bvc/480055/live_3117396_4657598_1500.m3u8?","url_info":[{"host":"https://d1--ov-gotcha105.bilivideo.com","extra":"expires=1698438667\u0026len=0\u0026oi=2283289789\u0026pt=web\u0026qn=0\u0026trid=10034866ef499f244853847fd6940f281c4f\u0026sigparams=cdn,expires,len,oi,pt,qn,trid\u0026cdn=ov-gotcha105\u0026sign=af52c73d7bff992327b655cf527e7e91\u0026sk=1304f646dfeb4df8b6e7ff33c167d3adda26bb4da5f21f1459ebf5b3c7780c72\u0026p2p_type=0\u0026sl=9\u0026free_type=0\u0026mid=0\u0026pp=rtmp\u0026source=onetier\u0026trace=0\u0026site=3fa9f3713b55c3df54c282427b025191\u0026order=1","stream_ttl":3600}],"hdr_qn":null,"dolby_type":0,"attr_name":""}]}]}],"p2p_data":{"p2p":false,"p2p_type":0,"m_p2p":false,"m_servers":null},"dolby_qn":null}},"official_type":0,"official_room_id":0}}
DEBUG:YKDL:'HD-bak'
Traceback (most recent call last):
  File "/Users/zizhengwu/git/ykdl/lib/python3.10/site-packages/cykdl/__main__.py", line 318, in main
    for rc in map(handle_video, args.video_urls):
  File "/Users/zizhengwu/git/ykdl/lib/python3.10/site-packages/cykdl/__main__.py", line 227, in handle_video
    info = parser(u)
  File "/Users/zizhengwu/git/ykdl/lib/python3.10/site-packages/ykdl/extractor.py", line 81, in parser
    info = self.prepare()
  File "/Users/zizhengwu/git/ykdl/lib/python3.10/site-packages/ykdl/extractors/bilibili/live.py", line 132, in prepare
    get_live_info()
  File "/Users/zizhengwu/git/ykdl/lib/python3.10/site-packages/ykdl/extractors/bilibili/live.py", line 130, in get_live_info
    get_live_info(qlt)
  File "/Users/zizhengwu/git/ykdl/lib/python3.10/site-packages/ykdl/extractors/bilibili/live.py", line 117, in get_live_info
    info.streams[st] = {
  File "/Users/zizhengwu/git/ykdl/lib/python3.10/site-packages/ykdl/mediainfo.py", line 219, in __setitem__
    self.set(name, value)
  File "/Users/zizhengwu/git/ykdl/lib/python3.10/site-packages/ykdl/mediainfo.py", line 260, in set
    raise KeyError(name)
KeyError: 'HD-bak'
```

如果你有其他附言，例如问题只在某个视频发生，或者是一般性讨论或者提出新功能，请在下面添加:

使用的是 git master branch 的最新版本

**Comment by fraic** [comment]
现在bilibili 需要登录才能获取高画质的流，否则不管传什么qn都只返回最低画质

v1版api反而还可以不登录使用……

**Comment by zizhengwu** [comment]
我现在暂时用 streamlink 看 bilibili 直播，发现好像可以用。

**Comment by SeaHOH** [comment]
恢复了 v1 API，暂时先用着吧。
